#!/usr/bin/env bash

set -euo pipefail

print_help() {
  printf '%s\n' \
    'Generate or check the committed Supabase database types.' \
    '' \
    'Usage:' \
    '  bash scripts/database-types.sh <generate|check> [python|web|all]' \
    '' \
    'Examples:' \
    '  bash scripts/database-types.sh generate' \
    '  bash scripts/database-types.sh generate web' \
    '  bash scripts/database-types.sh check'
}

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  print_help
  exit 0
fi

action="${1:-}"
target="${2:-all}"

if [[ $# -gt 2 || ( "$action" != "generate" && "$action" != "check" ) ]]; then
  printf 'Error: Expected generate or check.\n' >&2
  printf '  Example: bash scripts/database-types.sh check\n' >&2
  exit 2
fi

if [[ "$target" != "python" && "$target" != "web" && "$target" != "all" ]]; then
  printf 'Error: Expected python, web, or all.\n' >&2
  printf '  Example: bash scripts/database-types.sh generate web\n' >&2
  exit 2
fi

script_directory="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repository_root="$(cd -- "$script_directory/.." && pwd)"
temporary_directory="$(mktemp -d)"
trap 'rm -rf "$temporary_directory"' EXIT

cd "$repository_root"

database_type_path() {
  case "$1" in
    python)
      printf '%s\n' 'apps/backend/slowpoke_backend/database_types.py'
      ;;
    web)
      printf '%s\n' 'apps/web/src/lib/supabase/database.types.ts'
      ;;
  esac
}

generate_database_types() {
  local selected_target="$1"
  local output_file="$2"

  case "$selected_target" in
    python)
      {
        printf '%s\n' \
          '# Generated by `pnpm db:types`.' \
          '# Do not edit manually. Update the Supabase schema, reset the local database,' \
          '# then run `pnpm db:types`.'
        pnpm exec supabase gen types --lang=python --local --schema public
      } > "$output_file"
      ;;
    web)
      {
        printf '%s\n' \
          '// Generated by `pnpm db:types`.' \
          '// Do not edit manually. Update the Supabase schema, reset the local database,' \
          '// then run `pnpm db:types`.'
        pnpm exec supabase gen types --lang=typescript --local --schema public \
          | pnpm exec oxfmt --stdin-filepath apps/web/src/lib/supabase/database.types.ts
      } > "$output_file"
      ;;
  esac
}

if [[ "$target" == "all" ]]; then
  targets=(python web)
else
  targets=("$target")
fi

failed=0
for selected_target in "${targets[@]}"; do
  generated_file="$temporary_directory/$selected_target"
  committed_file="$(database_type_path "$selected_target")"
  generate_database_types "$selected_target" "$generated_file"

  if [[ "$action" == "generate" ]]; then
    cp "$generated_file" "$committed_file"
    continue
  fi

  if ! cmp -s "$generated_file" "$committed_file"; then
    if [[ "$selected_target" == "python" ]]; then
      target_label="Python"
    else
      target_label="Web"
    fi
    printf '%s database types have drifted. Run: pnpm db:types\n' \
      "$target_label" >&2
    failed=1
  fi
done

exit "$failed"
