#!/usr/bin/env bash

set -euo pipefail

printf '%s\n' \
  '// Generated by `pnpm db:types`.' \
  '// Do not edit manually. Update the Supabase schema, reset the local database,' \
  '// then run `pnpm db:types`.'

pnpm exec supabase gen types --lang=typescript --local --schema public \
  | pnpm exec oxfmt --stdin-filepath apps/web/src/lib/supabase/database.types.ts
