#!/usr/bin/env bash

set -euo pipefail

printf '%s\n' \
  '# Generated by `pnpm db:types`.' \
  '# Do not edit manually. Update the Supabase schema, reset the local database,' \
  '# then run `pnpm db:types`.'

pnpm exec supabase gen types --lang=python --local --schema public
