// Generated by `pnpm db:types`.
// Do not edit manually. Update the Supabase schema, reset the local database,
// then run `pnpm db:types`.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      installation_setup_sessions: {
        Row: {
          code_digest: string;
          created_at: string;
          created_by_user_id: string;
          expires_at: string;
          id: string;
          installation_type: string;
          organization_id: string;
          redeemed_at: string | null;
          selected_tools: string[];
        };
        Insert: {
          code_digest: string;
          created_at?: string;
          created_by_user_id: string;
          expires_at: string;
          id?: string;
          installation_type?: string;
          organization_id: string;
          redeemed_at?: string | null;
          selected_tools: string[];
        };
        Update: {
          code_digest?: string;
          created_at?: string;
          created_by_user_id?: string;
          expires_at?: string;
          id?: string;
          installation_type?: string;
          organization_id?: string;
          redeemed_at?: string | null;
          selected_tools?: string[];
        };
        Relationships: [
          {
            foreignKeyName: "installation_setup_sessions_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      installations: {
        Row: {
          computer_name: string;
          created_at: string;
          created_by_user_id: string;
          id: string;
          installation_type: string;
          last_seen_at: string | null;
          organization_id: string;
          revoked_at: string | null;
          setup_package_version: string | null;
          setup_session_id: string;
          tool: string;
          verified_at: string | null;
        };
        Insert: {
          computer_name: string;
          created_at?: string;
          created_by_user_id: string;
          id?: string;
          installation_type?: string;
          last_seen_at?: string | null;
          organization_id: string;
          revoked_at?: string | null;
          setup_package_version?: string | null;
          setup_session_id: string;
          tool: string;
          verified_at?: string | null;
        };
        Update: {
          computer_name?: string;
          created_at?: string;
          created_by_user_id?: string;
          id?: string;
          installation_type?: string;
          last_seen_at?: string | null;
          organization_id?: string;
          revoked_at?: string | null;
          setup_package_version?: string | null;
          setup_session_id?: string;
          tool?: string;
          verified_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "installations_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "installations_setup_session_id_organization_id_fkey";
            columns: ["setup_session_id", "organization_id"];
            isOneToOne: false;
            referencedRelation: "installation_setup_sessions";
            referencedColumns: ["id", "organization_id"];
          },
        ];
      };
      organization_invitations: {
        Row: {
          accepted_at: string | null;
          canceled_at: string | null;
          created_at: string;
          declined_at: string | null;
          expires_at: string;
          id: string;
          invited_by_user_id: string;
          normalized_email: string;
          organization_id: string;
          role: string;
          updated_at: string;
        };
        Insert: {
          accepted_at?: string | null;
          canceled_at?: string | null;
          created_at?: string;
          declined_at?: string | null;
          expires_at?: string;
          id?: string;
          invited_by_user_id: string;
          normalized_email: string;
          organization_id: string;
          role: string;
          updated_at?: string;
        };
        Update: {
          accepted_at?: string | null;
          canceled_at?: string | null;
          created_at?: string;
          declined_at?: string | null;
          expires_at?: string;
          id?: string;
          invited_by_user_id?: string;
          normalized_email?: string;
          organization_id?: string;
          role?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "organization_invitations_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      organization_members: {
        Row: {
          created_at: string;
          organization_id: string;
          role: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          organization_id: string;
          role: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          organization_id?: string;
          role?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "organization_members_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      organizations: {
        Row: {
          created_at: string;
          created_by_user_id: string;
          id: string;
          idempotency_key: string;
          logo_url: string | null;
          name: string;
        };
        Insert: {
          created_at?: string;
          created_by_user_id: string;
          id?: string;
          idempotency_key: string;
          logo_url?: string | null;
          name: string;
        };
        Update: {
          created_at?: string;
          created_by_user_id?: string;
          id?: string;
          idempotency_key?: string;
          logo_url?: string | null;
          name?: string;
        };
        Relationships: [];
      };
      prompt_events: {
        Row: {
          actor_account_id: string | null;
          actor_email: string | null;
          batch_id: string;
          created_at: string;
          event_name: string;
          id: string;
          installation_id: string;
          is_redacted: boolean;
          model: string | null;
          occurred_at: string;
          organization_id: string;
          originator: string | null;
          prompt_id: string | null;
          prompt_text: string;
          provider: string;
          record_index: number;
          session_id: string | null;
          slug: string | null;
        };
        Insert: {
          actor_account_id?: string | null;
          actor_email?: string | null;
          batch_id: string;
          created_at?: string;
          event_name: string;
          id?: string;
          installation_id: string;
          is_redacted?: boolean;
          model?: string | null;
          occurred_at: string;
          organization_id: string;
          originator?: string | null;
          prompt_id?: string | null;
          prompt_text: string;
          provider: string;
          record_index: number;
          session_id?: string | null;
          slug?: string | null;
        };
        Update: {
          actor_account_id?: string | null;
          actor_email?: string | null;
          batch_id?: string;
          created_at?: string;
          event_name?: string;
          id?: string;
          installation_id?: string;
          is_redacted?: boolean;
          model?: string | null;
          occurred_at?: string;
          organization_id?: string;
          originator?: string | null;
          prompt_id?: string | null;
          prompt_text?: string;
          provider?: string;
          record_index?: number;
          session_id?: string | null;
          slug?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "prompt_events_batch_id_organization_id_fkey";
            columns: ["batch_id", "organization_id"];
            isOneToOne: false;
            referencedRelation: "response_usage_events";
            referencedColumns: ["batch_id", "organization_id"];
          },
          {
            foreignKeyName: "prompt_events_batch_id_organization_id_fkey";
            columns: ["batch_id", "organization_id"];
            isOneToOne: false;
            referencedRelation: "telemetry_batches";
            referencedColumns: ["id", "organization_id"];
          },
          {
            foreignKeyName: "prompt_events_installation_id_organization_id_fkey";
            columns: ["installation_id", "organization_id"];
            isOneToOne: false;
            referencedRelation: "installations";
            referencedColumns: ["id", "organization_id"];
          },
          {
            foreignKeyName: "prompt_events_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      telemetry_batches: {
        Row: {
          content_sha256: string;
          id: string;
          installation_id: string;
          organization_id: string;
          raw_payload: Json;
          received_at: string;
          signal: string;
        };
        Insert: {
          content_sha256: string;
          id?: string;
          installation_id: string;
          organization_id: string;
          raw_payload: Json;
          received_at?: string;
          signal: string;
        };
        Update: {
          content_sha256?: string;
          id?: string;
          installation_id?: string;
          organization_id?: string;
          raw_payload?: Json;
          received_at?: string;
          signal?: string;
        };
        Relationships: [
          {
            foreignKeyName: "telemetry_batches_installation_id_organization_id_fkey";
            columns: ["installation_id", "organization_id"];
            isOneToOne: false;
            referencedRelation: "installations";
            referencedColumns: ["id", "organization_id"];
          },
          {
            foreignKeyName: "telemetry_batches_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: {
      human_prompt_events: {
        Row: {
          actor_account_id: string | null;
          actor_email: string | null;
          batch_id: string | null;
          created_at: string | null;
          event_name: string | null;
          id: string | null;
          installation_id: string | null;
          is_redacted: boolean | null;
          model: string | null;
          occurred_at: string | null;
          organization_id: string | null;
          originator: string | null;
          prompt_id: string | null;
          prompt_text: string | null;
          provider: string | null;
          record_index: number | null;
          session_id: string | null;
          slug: string | null;
        };
        Insert: {
          actor_account_id?: string | null;
          actor_email?: string | null;
          batch_id?: string | null;
          created_at?: string | null;
          event_name?: string | null;
          id?: string | null;
          installation_id?: string | null;
          is_redacted?: boolean | null;
          model?: string | null;
          occurred_at?: string | null;
          organization_id?: string | null;
          originator?: string | null;
          prompt_id?: string | null;
          prompt_text?: string | null;
          provider?: string | null;
          record_index?: number | null;
          session_id?: string | null;
          slug?: string | null;
        };
        Update: {
          actor_account_id?: string | null;
          actor_email?: string | null;
          batch_id?: string | null;
          created_at?: string | null;
          event_name?: string | null;
          id?: string | null;
          installation_id?: string | null;
          is_redacted?: boolean | null;
          model?: string | null;
          occurred_at?: string | null;
          organization_id?: string | null;
          originator?: string | null;
          prompt_id?: string | null;
          prompt_text?: string | null;
          provider?: string | null;
          record_index?: number | null;
          session_id?: string | null;
          slug?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "prompt_events_batch_id_organization_id_fkey";
            columns: ["batch_id", "organization_id"];
            isOneToOne: false;
            referencedRelation: "response_usage_events";
            referencedColumns: ["batch_id", "organization_id"];
          },
          {
            foreignKeyName: "prompt_events_batch_id_organization_id_fkey";
            columns: ["batch_id", "organization_id"];
            isOneToOne: false;
            referencedRelation: "telemetry_batches";
            referencedColumns: ["id", "organization_id"];
          },
          {
            foreignKeyName: "prompt_events_installation_id_organization_id_fkey";
            columns: ["installation_id", "organization_id"];
            isOneToOne: false;
            referencedRelation: "installations";
            referencedColumns: ["id", "organization_id"];
          },
          {
            foreignKeyName: "prompt_events_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      response_usage_events: {
        Row: {
          batch_id: string | null;
          cache_creation_token_count: string | null;
          cached_token_count: string | null;
          conversation_id: string | null;
          cost_usd: string | null;
          estimated_cost_usd: string | null;
          event_timestamp: string | null;
          input_token_count: string | null;
          installation_id: string | null;
          model: string | null;
          observed_time_unix_nano: string | null;
          organization_id: string | null;
          output_token_count: string | null;
          prompt_id: string | null;
          provider: string | null;
          reasoning_token_count: string | null;
          received_at: string | null;
          time_unix_nano: string | null;
          tool_token_count: string | null;
          total_cost_usd: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "telemetry_batches_installation_id_organization_id_fkey";
            columns: ["installation_id", "organization_id"];
            isOneToOne: false;
            referencedRelation: "installations";
            referencedColumns: ["id", "organization_id"];
          },
          {
            foreignKeyName: "telemetry_batches_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Functions: {
      get_prompt_analytics_daily: {
        Args: {
          p_days: number;
          p_end: string;
          p_organization_id: string;
          p_timezone: string;
        };
        Returns: {
          active_users: number;
          anthropic: number;
          day: string;
          openai: number;
          prompts: number;
        }[];
      };
      get_prompt_analytics_daily_users: {
        Args: {
          p_days: number;
          p_end: string;
          p_organization_id: string;
          p_timezone: string;
        };
        Returns: {
          day: string;
          prompts: number;
          rank: number;
          user_key: string;
          user_label: string;
        }[];
      };
      get_prompt_analytics_models: {
        Args: {
          p_days: number;
          p_end: string;
          p_organization_id: string;
          p_timezone: string;
        };
        Returns: {
          model: string;
          prompts: number;
        }[];
      };
      get_prompt_analytics_providers: {
        Args: {
          p_days: number;
          p_end: string;
          p_organization_id: string;
          p_timezone: string;
        };
        Returns: {
          prompts: number;
          provider: string;
        }[];
      };
      get_prompt_analytics_summary: {
        Args: {
          p_days: number;
          p_end: string;
          p_organization_id: string;
          p_timezone: string;
        };
        Returns: {
          current_active_users: number;
          current_prompts_per_day: number;
          current_prompts_per_user: number;
          current_total_prompts: number;
          previous_active_users: number;
          previous_prompts_per_day: number;
          previous_prompts_per_user: number;
          previous_total_prompts: number;
        }[];
      };
      get_prompt_analytics_users: {
        Args: {
          p_days: number;
          p_end: string;
          p_organization_id: string;
          p_timezone: string;
        };
        Returns: {
          last_active_at: string;
          prompts: number;
          rank: number;
          share: number;
          user_key: string;
          user_label: string;
        }[];
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
