# Generated by `pnpm db:types`.
# Do not edit manually. Update the Supabase schema, reset the local database,
# then run `pnpm db:types`.
from __future__ import annotations

import datetime
import uuid
from typing import (
    Annotated,
    Any,
    List,
    Literal,
    NotRequired,
    Optional,
    TypeAlias,
    TypedDict,
)

from pydantic import BaseModel, Field, Json

NetRequestStatus: TypeAlias = Literal["PENDING", "SUCCESS", "ERROR"]

StorageBuckettype: TypeAlias = Literal["STANDARD", "ANALYTICS", "VECTOR"]

AuthFactorType: TypeAlias = Literal["totp", "webauthn", "phone"]

AuthFactorStatus: TypeAlias = Literal["unverified", "verified"]

AuthAalLevel: TypeAlias = Literal["aal1", "aal2", "aal3"]

AuthCodeChallengeMethod: TypeAlias = Literal["s256", "plain"]

AuthOneTimeTokenType: TypeAlias = Literal["confirmation_token", "reauthentication_token", "recovery_token", "email_change_token_new", "email_change_token_current", "phone_change_token"]

AuthOauthRegistrationType: TypeAlias = Literal["dynamic", "manual"]

AuthOauthAuthorizationStatus: TypeAlias = Literal["pending", "approved", "denied", "expired"]

AuthOauthResponseType: TypeAlias = Literal["code"]

AuthOauthClientType: TypeAlias = Literal["public", "confidential"]

class PublicInstallations(BaseModel):
    computer_name: str = Field(alias="computer_name")
    created_at: datetime.datetime = Field(alias="created_at")
    created_by_user_id: uuid.UUID = Field(alias="created_by_user_id")
    id: uuid.UUID = Field(alias="id")
    last_seen_at: Optional[datetime.datetime] = Field(alias="last_seen_at")
    organization_id: uuid.UUID = Field(alias="organization_id")
    revoked_at: Optional[datetime.datetime] = Field(alias="revoked_at")
    setup_session_id: uuid.UUID = Field(alias="setup_session_id")
    tool: str = Field(alias="tool")
    verified_at: Optional[datetime.datetime] = Field(alias="verified_at")

class PublicInstallationsInsert(TypedDict):
    computer_name: Annotated[str, Field(alias="computer_name")]
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]
    created_by_user_id: Annotated[uuid.UUID, Field(alias="created_by_user_id")]
    id: NotRequired[Annotated[uuid.UUID, Field(alias="id")]]
    last_seen_at: NotRequired[Annotated[Optional[datetime.datetime], Field(alias="last_seen_at")]]
    organization_id: Annotated[uuid.UUID, Field(alias="organization_id")]
    revoked_at: NotRequired[Annotated[Optional[datetime.datetime], Field(alias="revoked_at")]]
    setup_session_id: Annotated[uuid.UUID, Field(alias="setup_session_id")]
    tool: Annotated[str, Field(alias="tool")]
    verified_at: NotRequired[Annotated[Optional[datetime.datetime], Field(alias="verified_at")]]

class PublicInstallationsUpdate(TypedDict):
    computer_name: NotRequired[Annotated[str, Field(alias="computer_name")]]
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]
    created_by_user_id: NotRequired[Annotated[uuid.UUID, Field(alias="created_by_user_id")]]
    id: NotRequired[Annotated[uuid.UUID, Field(alias="id")]]
    last_seen_at: NotRequired[Annotated[Optional[datetime.datetime], Field(alias="last_seen_at")]]
    organization_id: NotRequired[Annotated[uuid.UUID, Field(alias="organization_id")]]
    revoked_at: NotRequired[Annotated[Optional[datetime.datetime], Field(alias="revoked_at")]]
    setup_session_id: NotRequired[Annotated[uuid.UUID, Field(alias="setup_session_id")]]
    tool: NotRequired[Annotated[str, Field(alias="tool")]]
    verified_at: NotRequired[Annotated[Optional[datetime.datetime], Field(alias="verified_at")]]

class PublicOrganizationMembers(BaseModel):
    created_at: datetime.datetime = Field(alias="created_at")
    organization_id: uuid.UUID = Field(alias="organization_id")
    role: str = Field(alias="role")
    user_id: uuid.UUID = Field(alias="user_id")

class PublicOrganizationMembersInsert(TypedDict):
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]
    organization_id: Annotated[uuid.UUID, Field(alias="organization_id")]
    role: Annotated[str, Field(alias="role")]
    user_id: Annotated[uuid.UUID, Field(alias="user_id")]

class PublicOrganizationMembersUpdate(TypedDict):
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]
    organization_id: NotRequired[Annotated[uuid.UUID, Field(alias="organization_id")]]
    role: NotRequired[Annotated[str, Field(alias="role")]]
    user_id: NotRequired[Annotated[uuid.UUID, Field(alias="user_id")]]

class PublicOrganizations(BaseModel):
    created_at: datetime.datetime = Field(alias="created_at")
    created_by_user_id: uuid.UUID = Field(alias="created_by_user_id")
    id: uuid.UUID = Field(alias="id")
    idempotency_key: uuid.UUID = Field(alias="idempotency_key")
    logo_url: Optional[str] = Field(alias="logo_url")
    name: str = Field(alias="name")

class PublicOrganizationsInsert(TypedDict):
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]
    created_by_user_id: Annotated[uuid.UUID, Field(alias="created_by_user_id")]
    id: NotRequired[Annotated[uuid.UUID, Field(alias="id")]]
    idempotency_key: Annotated[uuid.UUID, Field(alias="idempotency_key")]
    logo_url: NotRequired[Annotated[Optional[str], Field(alias="logo_url")]]
    name: Annotated[str, Field(alias="name")]

class PublicOrganizationsUpdate(TypedDict):
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]
    created_by_user_id: NotRequired[Annotated[uuid.UUID, Field(alias="created_by_user_id")]]
    id: NotRequired[Annotated[uuid.UUID, Field(alias="id")]]
    idempotency_key: NotRequired[Annotated[uuid.UUID, Field(alias="idempotency_key")]]
    logo_url: NotRequired[Annotated[Optional[str], Field(alias="logo_url")]]
    name: NotRequired[Annotated[str, Field(alias="name")]]

class PublicPromptEvents(BaseModel):
    actor_account_id: Optional[str] = Field(alias="actor_account_id")
    actor_email: Optional[str] = Field(alias="actor_email")
    batch_id: uuid.UUID = Field(alias="batch_id")
    created_at: datetime.datetime = Field(alias="created_at")
    event_name: str = Field(alias="event_name")
    id: uuid.UUID = Field(alias="id")
    installation_id: uuid.UUID = Field(alias="installation_id")
    is_redacted: bool = Field(alias="is_redacted")
    model: Optional[str] = Field(alias="model")
    occurred_at: datetime.datetime = Field(alias="occurred_at")
    organization_id: uuid.UUID = Field(alias="organization_id")
    originator: Optional[str] = Field(alias="originator")
    prompt_id: Optional[str] = Field(alias="prompt_id")
    prompt_text: str = Field(alias="prompt_text")
    provider: str = Field(alias="provider")
    record_index: int = Field(alias="record_index")
    session_id: Optional[str] = Field(alias="session_id")
    slug: Optional[str] = Field(alias="slug")

class PublicPromptEventsInsert(TypedDict):
    actor_account_id: NotRequired[Annotated[Optional[str], Field(alias="actor_account_id")]]
    actor_email: NotRequired[Annotated[Optional[str], Field(alias="actor_email")]]
    batch_id: Annotated[uuid.UUID, Field(alias="batch_id")]
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]
    event_name: Annotated[str, Field(alias="event_name")]
    id: NotRequired[Annotated[uuid.UUID, Field(alias="id")]]
    installation_id: Annotated[uuid.UUID, Field(alias="installation_id")]
    is_redacted: NotRequired[Annotated[bool, Field(alias="is_redacted")]]
    model: NotRequired[Annotated[Optional[str], Field(alias="model")]]
    occurred_at: Annotated[datetime.datetime, Field(alias="occurred_at")]
    organization_id: Annotated[uuid.UUID, Field(alias="organization_id")]
    originator: NotRequired[Annotated[Optional[str], Field(alias="originator")]]
    prompt_id: NotRequired[Annotated[Optional[str], Field(alias="prompt_id")]]
    prompt_text: Annotated[str, Field(alias="prompt_text")]
    provider: Annotated[str, Field(alias="provider")]
    record_index: Annotated[int, Field(alias="record_index")]
    session_id: NotRequired[Annotated[Optional[str], Field(alias="session_id")]]
    slug: NotRequired[Annotated[Optional[str], Field(alias="slug")]]

class PublicPromptEventsUpdate(TypedDict):
    actor_account_id: NotRequired[Annotated[Optional[str], Field(alias="actor_account_id")]]
    actor_email: NotRequired[Annotated[Optional[str], Field(alias="actor_email")]]
    batch_id: NotRequired[Annotated[uuid.UUID, Field(alias="batch_id")]]
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]
    event_name: NotRequired[Annotated[str, Field(alias="event_name")]]
    id: NotRequired[Annotated[uuid.UUID, Field(alias="id")]]
    installation_id: NotRequired[Annotated[uuid.UUID, Field(alias="installation_id")]]
    is_redacted: NotRequired[Annotated[bool, Field(alias="is_redacted")]]
    model: NotRequired[Annotated[Optional[str], Field(alias="model")]]
    occurred_at: NotRequired[Annotated[datetime.datetime, Field(alias="occurred_at")]]
    organization_id: NotRequired[Annotated[uuid.UUID, Field(alias="organization_id")]]
    originator: NotRequired[Annotated[Optional[str], Field(alias="originator")]]
    prompt_id: NotRequired[Annotated[Optional[str], Field(alias="prompt_id")]]
    prompt_text: NotRequired[Annotated[str, Field(alias="prompt_text")]]
    provider: NotRequired[Annotated[str, Field(alias="provider")]]
    record_index: NotRequired[Annotated[int, Field(alias="record_index")]]
    session_id: NotRequired[Annotated[Optional[str], Field(alias="session_id")]]
    slug: NotRequired[Annotated[Optional[str], Field(alias="slug")]]

class PublicTelemetryBatches(BaseModel):
    content_sha256: str = Field(alias="content_sha256")
    id: uuid.UUID = Field(alias="id")
    installation_id: uuid.UUID = Field(alias="installation_id")
    organization_id: uuid.UUID = Field(alias="organization_id")
    raw_payload: Json[Any] = Field(alias="raw_payload")
    received_at: datetime.datetime = Field(alias="received_at")
    signal: str = Field(alias="signal")

class PublicTelemetryBatchesInsert(TypedDict):
    content_sha256: Annotated[str, Field(alias="content_sha256")]
    id: NotRequired[Annotated[uuid.UUID, Field(alias="id")]]
    installation_id: Annotated[uuid.UUID, Field(alias="installation_id")]
    organization_id: Annotated[uuid.UUID, Field(alias="organization_id")]
    raw_payload: Annotated[Json[Any], Field(alias="raw_payload")]
    received_at: NotRequired[Annotated[datetime.datetime, Field(alias="received_at")]]
    signal: Annotated[str, Field(alias="signal")]

class PublicTelemetryBatchesUpdate(TypedDict):
    content_sha256: NotRequired[Annotated[str, Field(alias="content_sha256")]]
    id: NotRequired[Annotated[uuid.UUID, Field(alias="id")]]
    installation_id: NotRequired[Annotated[uuid.UUID, Field(alias="installation_id")]]
    organization_id: NotRequired[Annotated[uuid.UUID, Field(alias="organization_id")]]
    raw_payload: NotRequired[Annotated[Json[Any], Field(alias="raw_payload")]]
    received_at: NotRequired[Annotated[datetime.datetime, Field(alias="received_at")]]
    signal: NotRequired[Annotated[str, Field(alias="signal")]]

class PublicOrganizationInvitations(BaseModel):
    accepted_at: Optional[datetime.datetime] = Field(alias="accepted_at")
    canceled_at: Optional[datetime.datetime] = Field(alias="canceled_at")
    created_at: datetime.datetime = Field(alias="created_at")
    declined_at: Optional[datetime.datetime] = Field(alias="declined_at")
    expires_at: datetime.datetime = Field(alias="expires_at")
    id: uuid.UUID = Field(alias="id")
    invited_by_user_id: uuid.UUID = Field(alias="invited_by_user_id")
    normalized_email: str = Field(alias="normalized_email")
    organization_id: uuid.UUID = Field(alias="organization_id")
    role: str = Field(alias="role")
    updated_at: datetime.datetime = Field(alias="updated_at")

class PublicOrganizationInvitationsInsert(TypedDict):
    accepted_at: NotRequired[Annotated[Optional[datetime.datetime], Field(alias="accepted_at")]]
    canceled_at: NotRequired[Annotated[Optional[datetime.datetime], Field(alias="canceled_at")]]
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]
    declined_at: NotRequired[Annotated[Optional[datetime.datetime], Field(alias="declined_at")]]
    expires_at: NotRequired[Annotated[datetime.datetime, Field(alias="expires_at")]]
    id: NotRequired[Annotated[uuid.UUID, Field(alias="id")]]
    invited_by_user_id: Annotated[uuid.UUID, Field(alias="invited_by_user_id")]
    normalized_email: Annotated[str, Field(alias="normalized_email")]
    organization_id: Annotated[uuid.UUID, Field(alias="organization_id")]
    role: Annotated[str, Field(alias="role")]
    updated_at: NotRequired[Annotated[datetime.datetime, Field(alias="updated_at")]]

class PublicOrganizationInvitationsUpdate(TypedDict):
    accepted_at: NotRequired[Annotated[Optional[datetime.datetime], Field(alias="accepted_at")]]
    canceled_at: NotRequired[Annotated[Optional[datetime.datetime], Field(alias="canceled_at")]]
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]
    declined_at: NotRequired[Annotated[Optional[datetime.datetime], Field(alias="declined_at")]]
    expires_at: NotRequired[Annotated[datetime.datetime, Field(alias="expires_at")]]
    id: NotRequired[Annotated[uuid.UUID, Field(alias="id")]]
    invited_by_user_id: NotRequired[Annotated[uuid.UUID, Field(alias="invited_by_user_id")]]
    normalized_email: NotRequired[Annotated[str, Field(alias="normalized_email")]]
    organization_id: NotRequired[Annotated[uuid.UUID, Field(alias="organization_id")]]
    role: NotRequired[Annotated[str, Field(alias="role")]]
    updated_at: NotRequired[Annotated[datetime.datetime, Field(alias="updated_at")]]

class PublicInstallationSetupSessions(BaseModel):
    code_digest: str = Field(alias="code_digest")
    created_at: datetime.datetime = Field(alias="created_at")
    created_by_user_id: uuid.UUID = Field(alias="created_by_user_id")
    expires_at: datetime.datetime = Field(alias="expires_at")
    id: uuid.UUID = Field(alias="id")
    organization_id: uuid.UUID = Field(alias="organization_id")
    redeemed_at: Optional[datetime.datetime] = Field(alias="redeemed_at")
    selected_tools: List[str] = Field(alias="selected_tools")

class PublicInstallationSetupSessionsInsert(TypedDict):
    code_digest: Annotated[str, Field(alias="code_digest")]
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]
    created_by_user_id: Annotated[uuid.UUID, Field(alias="created_by_user_id")]
    expires_at: Annotated[datetime.datetime, Field(alias="expires_at")]
    id: NotRequired[Annotated[uuid.UUID, Field(alias="id")]]
    organization_id: Annotated[uuid.UUID, Field(alias="organization_id")]
    redeemed_at: NotRequired[Annotated[Optional[datetime.datetime], Field(alias="redeemed_at")]]
    selected_tools: Annotated[List[str], Field(alias="selected_tools")]

class PublicInstallationSetupSessionsUpdate(TypedDict):
    code_digest: NotRequired[Annotated[str, Field(alias="code_digest")]]
    created_at: NotRequired[Annotated[datetime.datetime, Field(alias="created_at")]]
    created_by_user_id: NotRequired[Annotated[uuid.UUID, Field(alias="created_by_user_id")]]
    expires_at: NotRequired[Annotated[datetime.datetime, Field(alias="expires_at")]]
    id: NotRequired[Annotated[uuid.UUID, Field(alias="id")]]
    organization_id: NotRequired[Annotated[uuid.UUID, Field(alias="organization_id")]]
    redeemed_at: NotRequired[Annotated[Optional[datetime.datetime], Field(alias="redeemed_at")]]
    selected_tools: NotRequired[Annotated[List[str], Field(alias="selected_tools")]]

class PublicResponseUsageEvents(BaseModel):
    batch_id: Optional[uuid.UUID] = Field(alias="batch_id")
    cache_creation_token_count: Optional[str] = Field(alias="cache_creation_token_count")
    cached_token_count: Optional[str] = Field(alias="cached_token_count")
    conversation_id: Optional[str] = Field(alias="conversation_id")
    cost_usd: Optional[str] = Field(alias="cost_usd")
    estimated_cost_usd: Optional[str] = Field(alias="estimated_cost_usd")
    event_timestamp: Optional[str] = Field(alias="event_timestamp")
    input_token_count: Optional[str] = Field(alias="input_token_count")
    installation_id: Optional[uuid.UUID] = Field(alias="installation_id")
    model: Optional[str] = Field(alias="model")
    observed_time_unix_nano: Optional[str] = Field(alias="observed_time_unix_nano")
    organization_id: Optional[uuid.UUID] = Field(alias="organization_id")
    output_token_count: Optional[str] = Field(alias="output_token_count")
    prompt_id: Optional[str] = Field(alias="prompt_id")
    provider: Optional[str] = Field(alias="provider")
    reasoning_token_count: Optional[str] = Field(alias="reasoning_token_count")
    received_at: Optional[datetime.datetime] = Field(alias="received_at")
    time_unix_nano: Optional[str] = Field(alias="time_unix_nano")
    tool_token_count: Optional[str] = Field(alias="tool_token_count")
    total_cost_usd: Optional[str] = Field(alias="total_cost_usd")

class PublicHumanPromptEvents(BaseModel):
    actor_account_id: Optional[str] = Field(alias="actor_account_id")
    actor_email: Optional[str] = Field(alias="actor_email")
    batch_id: Optional[uuid.UUID] = Field(alias="batch_id")
    created_at: Optional[datetime.datetime] = Field(alias="created_at")
    event_name: Optional[str] = Field(alias="event_name")
    id: Optional[uuid.UUID] = Field(alias="id")
    installation_id: Optional[uuid.UUID] = Field(alias="installation_id")
    is_redacted: Optional[bool] = Field(alias="is_redacted")
    model: Optional[str] = Field(alias="model")
    occurred_at: Optional[datetime.datetime] = Field(alias="occurred_at")
    organization_id: Optional[uuid.UUID] = Field(alias="organization_id")
    originator: Optional[str] = Field(alias="originator")
    prompt_id: Optional[str] = Field(alias="prompt_id")
    prompt_text: Optional[str] = Field(alias="prompt_text")
    provider: Optional[str] = Field(alias="provider")
    record_index: Optional[int] = Field(alias="record_index")
    session_id: Optional[str] = Field(alias="session_id")
    slug: Optional[str] = Field(alias="slug")
